// These are the ids for yahoo's stats
export const statIdToNameMap = {
	'careerGP': 'career GP',
	'name': 'Player',
	'team': 'Team',
	'position': 'Position',
	'P/G': "Points Per Game",
	'0': 'Games Played',
	'1': 'Goals',
	'2': 'Assists',
	'3': 'Points',
	'4': 'Plus/Minus',
	'5': 'Penalties in Minutes',
	'6' : 'Power Play Goals',
	'7' : 'Power Play Assists',
	'8': 'Power Play Points',
	'9' : 'Shorthanded Goals',
	'10' : 'Shorthanded Assists',
	'11' : '',
	'12' : '',
	'13' : '',
	'14': 'Shots On Goal',
	'15': 'Shooting Percentage',
	'16': 'Faceoffs Won',
	'17' : 'Faceoffs Lost',
	'18' : 'Games Started',
	'19' : 'Wins',
	'20' : '',
	'21' : '',
	'22' : 'Goals Against',
	'23' : 'Goals Against Average',
	'24' : 'Shots Against',
	'25' : 'Saves',
	'26' : 'Save Percentage',
	'27' : '',
	'28' : '',
	'29' : '',
	'30' : '',
	'31': 'Hits',
	'32': 'Blocks',
	'percent_drafted': '% Drafted',
	'average_pick': 'Average Pick',
}
